
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ImmagineImmobile` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ImmagineImmobile
 * 
 */
export type ImmagineImmobileModel = runtime.Types.Result.DefaultSelection<Prisma.$ImmagineImmobilePayload>

export type AggregateImmagineImmobile = {
  _count: ImmagineImmobileCountAggregateOutputType | null
  _min: ImmagineImmobileMinAggregateOutputType | null
  _max: ImmagineImmobileMaxAggregateOutputType | null
}

export type ImmagineImmobileMinAggregateOutputType = {
  id: string | null
  immobileId: string | null
  url: string | null
  isCover: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ImmagineImmobileMaxAggregateOutputType = {
  id: string | null
  immobileId: string | null
  url: string | null
  isCover: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ImmagineImmobileCountAggregateOutputType = {
  id: number
  immobileId: number
  url: number
  isCover: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type ImmagineImmobileMinAggregateInputType = {
  id?: true
  immobileId?: true
  url?: true
  isCover?: true
  createdAt?: true
  updatedAt?: true
}

export type ImmagineImmobileMaxAggregateInputType = {
  id?: true
  immobileId?: true
  url?: true
  isCover?: true
  createdAt?: true
  updatedAt?: true
}

export type ImmagineImmobileCountAggregateInputType = {
  id?: true
  immobileId?: true
  url?: true
  isCover?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type ImmagineImmobileAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ImmagineImmobile to aggregate.
   */
  where?: Prisma.ImmagineImmobileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ImmagineImmobiles to fetch.
   */
  orderBy?: Prisma.ImmagineImmobileOrderByWithRelationInput | Prisma.ImmagineImmobileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ImmagineImmobileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ImmagineImmobiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ImmagineImmobiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ImmagineImmobiles
  **/
  _count?: true | ImmagineImmobileCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ImmagineImmobileMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ImmagineImmobileMaxAggregateInputType
}

export type GetImmagineImmobileAggregateType<T extends ImmagineImmobileAggregateArgs> = {
      [P in keyof T & keyof AggregateImmagineImmobile]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateImmagineImmobile[P]>
    : Prisma.GetScalarType<T[P], AggregateImmagineImmobile[P]>
}




export type ImmagineImmobileGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ImmagineImmobileWhereInput
  orderBy?: Prisma.ImmagineImmobileOrderByWithAggregationInput | Prisma.ImmagineImmobileOrderByWithAggregationInput[]
  by: Prisma.ImmagineImmobileScalarFieldEnum[] | Prisma.ImmagineImmobileScalarFieldEnum
  having?: Prisma.ImmagineImmobileScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ImmagineImmobileCountAggregateInputType | true
  _min?: ImmagineImmobileMinAggregateInputType
  _max?: ImmagineImmobileMaxAggregateInputType
}

export type ImmagineImmobileGroupByOutputType = {
  id: string
  immobileId: string
  url: string
  isCover: boolean
  createdAt: Date
  updatedAt: Date
  _count: ImmagineImmobileCountAggregateOutputType | null
  _min: ImmagineImmobileMinAggregateOutputType | null
  _max: ImmagineImmobileMaxAggregateOutputType | null
}

export type GetImmagineImmobileGroupByPayload<T extends ImmagineImmobileGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ImmagineImmobileGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ImmagineImmobileGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ImmagineImmobileGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ImmagineImmobileGroupByOutputType[P]>
      }
    >
  >



export type ImmagineImmobileWhereInput = {
  AND?: Prisma.ImmagineImmobileWhereInput | Prisma.ImmagineImmobileWhereInput[]
  OR?: Prisma.ImmagineImmobileWhereInput[]
  NOT?: Prisma.ImmagineImmobileWhereInput | Prisma.ImmagineImmobileWhereInput[]
  id?: Prisma.StringFilter<"ImmagineImmobile"> | string
  immobileId?: Prisma.StringFilter<"ImmagineImmobile"> | string
  url?: Prisma.StringFilter<"ImmagineImmobile"> | string
  isCover?: Prisma.BoolFilter<"ImmagineImmobile"> | boolean
  createdAt?: Prisma.DateTimeFilter<"ImmagineImmobile"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ImmagineImmobile"> | Date | string
  immobile?: Prisma.XOR<Prisma.ImmobileScalarRelationFilter, Prisma.ImmobileWhereInput>
}

export type ImmagineImmobileOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  immobileId?: Prisma.SortOrder
  url?: Prisma.SortOrder
  isCover?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  immobile?: Prisma.ImmobileOrderByWithRelationInput
}

export type ImmagineImmobileWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  url?: string
  AND?: Prisma.ImmagineImmobileWhereInput | Prisma.ImmagineImmobileWhereInput[]
  OR?: Prisma.ImmagineImmobileWhereInput[]
  NOT?: Prisma.ImmagineImmobileWhereInput | Prisma.ImmagineImmobileWhereInput[]
  immobileId?: Prisma.StringFilter<"ImmagineImmobile"> | string
  isCover?: Prisma.BoolFilter<"ImmagineImmobile"> | boolean
  createdAt?: Prisma.DateTimeFilter<"ImmagineImmobile"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ImmagineImmobile"> | Date | string
  immobile?: Prisma.XOR<Prisma.ImmobileScalarRelationFilter, Prisma.ImmobileWhereInput>
}, "id" | "url">

export type ImmagineImmobileOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  immobileId?: Prisma.SortOrder
  url?: Prisma.SortOrder
  isCover?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.ImmagineImmobileCountOrderByAggregateInput
  _max?: Prisma.ImmagineImmobileMaxOrderByAggregateInput
  _min?: Prisma.ImmagineImmobileMinOrderByAggregateInput
}

export type ImmagineImmobileScalarWhereWithAggregatesInput = {
  AND?: Prisma.ImmagineImmobileScalarWhereWithAggregatesInput | Prisma.ImmagineImmobileScalarWhereWithAggregatesInput[]
  OR?: Prisma.ImmagineImmobileScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ImmagineImmobileScalarWhereWithAggregatesInput | Prisma.ImmagineImmobileScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ImmagineImmobile"> | string
  immobileId?: Prisma.StringWithAggregatesFilter<"ImmagineImmobile"> | string
  url?: Prisma.StringWithAggregatesFilter<"ImmagineImmobile"> | string
  isCover?: Prisma.BoolWithAggregatesFilter<"ImmagineImmobile"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"ImmagineImmobile"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"ImmagineImmobile"> | Date | string
}

export type ImmagineImmobileCreateInput = {
  id?: string
  url: string
  isCover?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  immobile: Prisma.ImmobileCreateNestedOneWithoutImmaginiInput
}

export type ImmagineImmobileUncheckedCreateInput = {
  id?: string
  immobileId: string
  url: string
  isCover?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ImmagineImmobileUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  isCover?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  immobile?: Prisma.ImmobileUpdateOneRequiredWithoutImmaginiNestedInput
}

export type ImmagineImmobileUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  immobileId?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  isCover?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ImmagineImmobileCreateManyInput = {
  id?: string
  immobileId: string
  url: string
  isCover?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ImmagineImmobileUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  isCover?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ImmagineImmobileUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  immobileId?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  isCover?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ImmagineImmobileListRelationFilter = {
  every?: Prisma.ImmagineImmobileWhereInput
  some?: Prisma.ImmagineImmobileWhereInput
  none?: Prisma.ImmagineImmobileWhereInput
}

export type ImmagineImmobileOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ImmagineImmobileCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  immobileId?: Prisma.SortOrder
  url?: Prisma.SortOrder
  isCover?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ImmagineImmobileMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  immobileId?: Prisma.SortOrder
  url?: Prisma.SortOrder
  isCover?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ImmagineImmobileMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  immobileId?: Prisma.SortOrder
  url?: Prisma.SortOrder
  isCover?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ImmagineImmobileCreateNestedManyWithoutImmobileInput = {
  create?: Prisma.XOR<Prisma.ImmagineImmobileCreateWithoutImmobileInput, Prisma.ImmagineImmobileUncheckedCreateWithoutImmobileInput> | Prisma.ImmagineImmobileCreateWithoutImmobileInput[] | Prisma.ImmagineImmobileUncheckedCreateWithoutImmobileInput[]
  connectOrCreate?: Prisma.ImmagineImmobileCreateOrConnectWithoutImmobileInput | Prisma.ImmagineImmobileCreateOrConnectWithoutImmobileInput[]
  createMany?: Prisma.ImmagineImmobileCreateManyImmobileInputEnvelope
  connect?: Prisma.ImmagineImmobileWhereUniqueInput | Prisma.ImmagineImmobileWhereUniqueInput[]
}

export type ImmagineImmobileUncheckedCreateNestedManyWithoutImmobileInput = {
  create?: Prisma.XOR<Prisma.ImmagineImmobileCreateWithoutImmobileInput, Prisma.ImmagineImmobileUncheckedCreateWithoutImmobileInput> | Prisma.ImmagineImmobileCreateWithoutImmobileInput[] | Prisma.ImmagineImmobileUncheckedCreateWithoutImmobileInput[]
  connectOrCreate?: Prisma.ImmagineImmobileCreateOrConnectWithoutImmobileInput | Prisma.ImmagineImmobileCreateOrConnectWithoutImmobileInput[]
  createMany?: Prisma.ImmagineImmobileCreateManyImmobileInputEnvelope
  connect?: Prisma.ImmagineImmobileWhereUniqueInput | Prisma.ImmagineImmobileWhereUniqueInput[]
}

export type ImmagineImmobileUpdateManyWithoutImmobileNestedInput = {
  create?: Prisma.XOR<Prisma.ImmagineImmobileCreateWithoutImmobileInput, Prisma.ImmagineImmobileUncheckedCreateWithoutImmobileInput> | Prisma.ImmagineImmobileCreateWithoutImmobileInput[] | Prisma.ImmagineImmobileUncheckedCreateWithoutImmobileInput[]
  connectOrCreate?: Prisma.ImmagineImmobileCreateOrConnectWithoutImmobileInput | Prisma.ImmagineImmobileCreateOrConnectWithoutImmobileInput[]
  upsert?: Prisma.ImmagineImmobileUpsertWithWhereUniqueWithoutImmobileInput | Prisma.ImmagineImmobileUpsertWithWhereUniqueWithoutImmobileInput[]
  createMany?: Prisma.ImmagineImmobileCreateManyImmobileInputEnvelope
  set?: Prisma.ImmagineImmobileWhereUniqueInput | Prisma.ImmagineImmobileWhereUniqueInput[]
  disconnect?: Prisma.ImmagineImmobileWhereUniqueInput | Prisma.ImmagineImmobileWhereUniqueInput[]
  delete?: Prisma.ImmagineImmobileWhereUniqueInput | Prisma.ImmagineImmobileWhereUniqueInput[]
  connect?: Prisma.ImmagineImmobileWhereUniqueInput | Prisma.ImmagineImmobileWhereUniqueInput[]
  update?: Prisma.ImmagineImmobileUpdateWithWhereUniqueWithoutImmobileInput | Prisma.ImmagineImmobileUpdateWithWhereUniqueWithoutImmobileInput[]
  updateMany?: Prisma.ImmagineImmobileUpdateManyWithWhereWithoutImmobileInput | Prisma.ImmagineImmobileUpdateManyWithWhereWithoutImmobileInput[]
  deleteMany?: Prisma.ImmagineImmobileScalarWhereInput | Prisma.ImmagineImmobileScalarWhereInput[]
}

export type ImmagineImmobileUncheckedUpdateManyWithoutImmobileNestedInput = {
  create?: Prisma.XOR<Prisma.ImmagineImmobileCreateWithoutImmobileInput, Prisma.ImmagineImmobileUncheckedCreateWithoutImmobileInput> | Prisma.ImmagineImmobileCreateWithoutImmobileInput[] | Prisma.ImmagineImmobileUncheckedCreateWithoutImmobileInput[]
  connectOrCreate?: Prisma.ImmagineImmobileCreateOrConnectWithoutImmobileInput | Prisma.ImmagineImmobileCreateOrConnectWithoutImmobileInput[]
  upsert?: Prisma.ImmagineImmobileUpsertWithWhereUniqueWithoutImmobileInput | Prisma.ImmagineImmobileUpsertWithWhereUniqueWithoutImmobileInput[]
  createMany?: Prisma.ImmagineImmobileCreateManyImmobileInputEnvelope
  set?: Prisma.ImmagineImmobileWhereUniqueInput | Prisma.ImmagineImmobileWhereUniqueInput[]
  disconnect?: Prisma.ImmagineImmobileWhereUniqueInput | Prisma.ImmagineImmobileWhereUniqueInput[]
  delete?: Prisma.ImmagineImmobileWhereUniqueInput | Prisma.ImmagineImmobileWhereUniqueInput[]
  connect?: Prisma.ImmagineImmobileWhereUniqueInput | Prisma.ImmagineImmobileWhereUniqueInput[]
  update?: Prisma.ImmagineImmobileUpdateWithWhereUniqueWithoutImmobileInput | Prisma.ImmagineImmobileUpdateWithWhereUniqueWithoutImmobileInput[]
  updateMany?: Prisma.ImmagineImmobileUpdateManyWithWhereWithoutImmobileInput | Prisma.ImmagineImmobileUpdateManyWithWhereWithoutImmobileInput[]
  deleteMany?: Prisma.ImmagineImmobileScalarWhereInput | Prisma.ImmagineImmobileScalarWhereInput[]
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}

export type ImmagineImmobileCreateWithoutImmobileInput = {
  id?: string
  url: string
  isCover?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ImmagineImmobileUncheckedCreateWithoutImmobileInput = {
  id?: string
  url: string
  isCover?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ImmagineImmobileCreateOrConnectWithoutImmobileInput = {
  where: Prisma.ImmagineImmobileWhereUniqueInput
  create: Prisma.XOR<Prisma.ImmagineImmobileCreateWithoutImmobileInput, Prisma.ImmagineImmobileUncheckedCreateWithoutImmobileInput>
}

export type ImmagineImmobileCreateManyImmobileInputEnvelope = {
  data: Prisma.ImmagineImmobileCreateManyImmobileInput | Prisma.ImmagineImmobileCreateManyImmobileInput[]
  skipDuplicates?: boolean
}

export type ImmagineImmobileUpsertWithWhereUniqueWithoutImmobileInput = {
  where: Prisma.ImmagineImmobileWhereUniqueInput
  update: Prisma.XOR<Prisma.ImmagineImmobileUpdateWithoutImmobileInput, Prisma.ImmagineImmobileUncheckedUpdateWithoutImmobileInput>
  create: Prisma.XOR<Prisma.ImmagineImmobileCreateWithoutImmobileInput, Prisma.ImmagineImmobileUncheckedCreateWithoutImmobileInput>
}

export type ImmagineImmobileUpdateWithWhereUniqueWithoutImmobileInput = {
  where: Prisma.ImmagineImmobileWhereUniqueInput
  data: Prisma.XOR<Prisma.ImmagineImmobileUpdateWithoutImmobileInput, Prisma.ImmagineImmobileUncheckedUpdateWithoutImmobileInput>
}

export type ImmagineImmobileUpdateManyWithWhereWithoutImmobileInput = {
  where: Prisma.ImmagineImmobileScalarWhereInput
  data: Prisma.XOR<Prisma.ImmagineImmobileUpdateManyMutationInput, Prisma.ImmagineImmobileUncheckedUpdateManyWithoutImmobileInput>
}

export type ImmagineImmobileScalarWhereInput = {
  AND?: Prisma.ImmagineImmobileScalarWhereInput | Prisma.ImmagineImmobileScalarWhereInput[]
  OR?: Prisma.ImmagineImmobileScalarWhereInput[]
  NOT?: Prisma.ImmagineImmobileScalarWhereInput | Prisma.ImmagineImmobileScalarWhereInput[]
  id?: Prisma.StringFilter<"ImmagineImmobile"> | string
  immobileId?: Prisma.StringFilter<"ImmagineImmobile"> | string
  url?: Prisma.StringFilter<"ImmagineImmobile"> | string
  isCover?: Prisma.BoolFilter<"ImmagineImmobile"> | boolean
  createdAt?: Prisma.DateTimeFilter<"ImmagineImmobile"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ImmagineImmobile"> | Date | string
}

export type ImmagineImmobileCreateManyImmobileInput = {
  id?: string
  url: string
  isCover?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ImmagineImmobileUpdateWithoutImmobileInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  isCover?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ImmagineImmobileUncheckedUpdateWithoutImmobileInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  isCover?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ImmagineImmobileUncheckedUpdateManyWithoutImmobileInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  isCover?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type ImmagineImmobileSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  immobileId?: boolean
  url?: boolean
  isCover?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  immobile?: boolean | Prisma.ImmobileDefaultArgs<ExtArgs>
}, ExtArgs["result"]["immagineImmobile"]>

export type ImmagineImmobileSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  immobileId?: boolean
  url?: boolean
  isCover?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  immobile?: boolean | Prisma.ImmobileDefaultArgs<ExtArgs>
}, ExtArgs["result"]["immagineImmobile"]>

export type ImmagineImmobileSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  immobileId?: boolean
  url?: boolean
  isCover?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  immobile?: boolean | Prisma.ImmobileDefaultArgs<ExtArgs>
}, ExtArgs["result"]["immagineImmobile"]>

export type ImmagineImmobileSelectScalar = {
  id?: boolean
  immobileId?: boolean
  url?: boolean
  isCover?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type ImmagineImmobileOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "immobileId" | "url" | "isCover" | "createdAt" | "updatedAt", ExtArgs["result"]["immagineImmobile"]>
export type ImmagineImmobileInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  immobile?: boolean | Prisma.ImmobileDefaultArgs<ExtArgs>
}
export type ImmagineImmobileIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  immobile?: boolean | Prisma.ImmobileDefaultArgs<ExtArgs>
}
export type ImmagineImmobileIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  immobile?: boolean | Prisma.ImmobileDefaultArgs<ExtArgs>
}

export type $ImmagineImmobilePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ImmagineImmobile"
  objects: {
    immobile: Prisma.$ImmobilePayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    immobileId: string
    url: string
    isCover: boolean
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["immagineImmobile"]>
  composites: {}
}

export type ImmagineImmobileGetPayload<S extends boolean | null | undefined | ImmagineImmobileDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ImmagineImmobilePayload, S>

export type ImmagineImmobileCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ImmagineImmobileFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ImmagineImmobileCountAggregateInputType | true
  }

export interface ImmagineImmobileDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ImmagineImmobile'], meta: { name: 'ImmagineImmobile' } }
  /**
   * Find zero or one ImmagineImmobile that matches the filter.
   * @param {ImmagineImmobileFindUniqueArgs} args - Arguments to find a ImmagineImmobile
   * @example
   * // Get one ImmagineImmobile
   * const immagineImmobile = await prisma.immagineImmobile.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ImmagineImmobileFindUniqueArgs>(args: Prisma.SelectSubset<T, ImmagineImmobileFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ImmagineImmobileClient<runtime.Types.Result.GetResult<Prisma.$ImmagineImmobilePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ImmagineImmobile that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ImmagineImmobileFindUniqueOrThrowArgs} args - Arguments to find a ImmagineImmobile
   * @example
   * // Get one ImmagineImmobile
   * const immagineImmobile = await prisma.immagineImmobile.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ImmagineImmobileFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ImmagineImmobileFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ImmagineImmobileClient<runtime.Types.Result.GetResult<Prisma.$ImmagineImmobilePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ImmagineImmobile that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ImmagineImmobileFindFirstArgs} args - Arguments to find a ImmagineImmobile
   * @example
   * // Get one ImmagineImmobile
   * const immagineImmobile = await prisma.immagineImmobile.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ImmagineImmobileFindFirstArgs>(args?: Prisma.SelectSubset<T, ImmagineImmobileFindFirstArgs<ExtArgs>>): Prisma.Prisma__ImmagineImmobileClient<runtime.Types.Result.GetResult<Prisma.$ImmagineImmobilePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ImmagineImmobile that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ImmagineImmobileFindFirstOrThrowArgs} args - Arguments to find a ImmagineImmobile
   * @example
   * // Get one ImmagineImmobile
   * const immagineImmobile = await prisma.immagineImmobile.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ImmagineImmobileFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ImmagineImmobileFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ImmagineImmobileClient<runtime.Types.Result.GetResult<Prisma.$ImmagineImmobilePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ImmagineImmobiles that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ImmagineImmobileFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ImmagineImmobiles
   * const immagineImmobiles = await prisma.immagineImmobile.findMany()
   * 
   * // Get first 10 ImmagineImmobiles
   * const immagineImmobiles = await prisma.immagineImmobile.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const immagineImmobileWithIdOnly = await prisma.immagineImmobile.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ImmagineImmobileFindManyArgs>(args?: Prisma.SelectSubset<T, ImmagineImmobileFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ImmagineImmobilePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ImmagineImmobile.
   * @param {ImmagineImmobileCreateArgs} args - Arguments to create a ImmagineImmobile.
   * @example
   * // Create one ImmagineImmobile
   * const ImmagineImmobile = await prisma.immagineImmobile.create({
   *   data: {
   *     // ... data to create a ImmagineImmobile
   *   }
   * })
   * 
   */
  create<T extends ImmagineImmobileCreateArgs>(args: Prisma.SelectSubset<T, ImmagineImmobileCreateArgs<ExtArgs>>): Prisma.Prisma__ImmagineImmobileClient<runtime.Types.Result.GetResult<Prisma.$ImmagineImmobilePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ImmagineImmobiles.
   * @param {ImmagineImmobileCreateManyArgs} args - Arguments to create many ImmagineImmobiles.
   * @example
   * // Create many ImmagineImmobiles
   * const immagineImmobile = await prisma.immagineImmobile.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ImmagineImmobileCreateManyArgs>(args?: Prisma.SelectSubset<T, ImmagineImmobileCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ImmagineImmobiles and returns the data saved in the database.
   * @param {ImmagineImmobileCreateManyAndReturnArgs} args - Arguments to create many ImmagineImmobiles.
   * @example
   * // Create many ImmagineImmobiles
   * const immagineImmobile = await prisma.immagineImmobile.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ImmagineImmobiles and only return the `id`
   * const immagineImmobileWithIdOnly = await prisma.immagineImmobile.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ImmagineImmobileCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ImmagineImmobileCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ImmagineImmobilePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ImmagineImmobile.
   * @param {ImmagineImmobileDeleteArgs} args - Arguments to delete one ImmagineImmobile.
   * @example
   * // Delete one ImmagineImmobile
   * const ImmagineImmobile = await prisma.immagineImmobile.delete({
   *   where: {
   *     // ... filter to delete one ImmagineImmobile
   *   }
   * })
   * 
   */
  delete<T extends ImmagineImmobileDeleteArgs>(args: Prisma.SelectSubset<T, ImmagineImmobileDeleteArgs<ExtArgs>>): Prisma.Prisma__ImmagineImmobileClient<runtime.Types.Result.GetResult<Prisma.$ImmagineImmobilePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ImmagineImmobile.
   * @param {ImmagineImmobileUpdateArgs} args - Arguments to update one ImmagineImmobile.
   * @example
   * // Update one ImmagineImmobile
   * const immagineImmobile = await prisma.immagineImmobile.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ImmagineImmobileUpdateArgs>(args: Prisma.SelectSubset<T, ImmagineImmobileUpdateArgs<ExtArgs>>): Prisma.Prisma__ImmagineImmobileClient<runtime.Types.Result.GetResult<Prisma.$ImmagineImmobilePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ImmagineImmobiles.
   * @param {ImmagineImmobileDeleteManyArgs} args - Arguments to filter ImmagineImmobiles to delete.
   * @example
   * // Delete a few ImmagineImmobiles
   * const { count } = await prisma.immagineImmobile.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ImmagineImmobileDeleteManyArgs>(args?: Prisma.SelectSubset<T, ImmagineImmobileDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ImmagineImmobiles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ImmagineImmobileUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ImmagineImmobiles
   * const immagineImmobile = await prisma.immagineImmobile.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ImmagineImmobileUpdateManyArgs>(args: Prisma.SelectSubset<T, ImmagineImmobileUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ImmagineImmobiles and returns the data updated in the database.
   * @param {ImmagineImmobileUpdateManyAndReturnArgs} args - Arguments to update many ImmagineImmobiles.
   * @example
   * // Update many ImmagineImmobiles
   * const immagineImmobile = await prisma.immagineImmobile.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ImmagineImmobiles and only return the `id`
   * const immagineImmobileWithIdOnly = await prisma.immagineImmobile.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ImmagineImmobileUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ImmagineImmobileUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ImmagineImmobilePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ImmagineImmobile.
   * @param {ImmagineImmobileUpsertArgs} args - Arguments to update or create a ImmagineImmobile.
   * @example
   * // Update or create a ImmagineImmobile
   * const immagineImmobile = await prisma.immagineImmobile.upsert({
   *   create: {
   *     // ... data to create a ImmagineImmobile
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ImmagineImmobile we want to update
   *   }
   * })
   */
  upsert<T extends ImmagineImmobileUpsertArgs>(args: Prisma.SelectSubset<T, ImmagineImmobileUpsertArgs<ExtArgs>>): Prisma.Prisma__ImmagineImmobileClient<runtime.Types.Result.GetResult<Prisma.$ImmagineImmobilePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ImmagineImmobiles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ImmagineImmobileCountArgs} args - Arguments to filter ImmagineImmobiles to count.
   * @example
   * // Count the number of ImmagineImmobiles
   * const count = await prisma.immagineImmobile.count({
   *   where: {
   *     // ... the filter for the ImmagineImmobiles we want to count
   *   }
   * })
  **/
  count<T extends ImmagineImmobileCountArgs>(
    args?: Prisma.Subset<T, ImmagineImmobileCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ImmagineImmobileCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ImmagineImmobile.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ImmagineImmobileAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ImmagineImmobileAggregateArgs>(args: Prisma.Subset<T, ImmagineImmobileAggregateArgs>): Prisma.PrismaPromise<GetImmagineImmobileAggregateType<T>>

  /**
   * Group by ImmagineImmobile.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ImmagineImmobileGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ImmagineImmobileGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ImmagineImmobileGroupByArgs['orderBy'] }
      : { orderBy?: ImmagineImmobileGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ImmagineImmobileGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetImmagineImmobileGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ImmagineImmobile model
 */
readonly fields: ImmagineImmobileFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ImmagineImmobile.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ImmagineImmobileClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  immobile<T extends Prisma.ImmobileDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ImmobileDefaultArgs<ExtArgs>>): Prisma.Prisma__ImmobileClient<runtime.Types.Result.GetResult<Prisma.$ImmobilePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ImmagineImmobile model
 */
export interface ImmagineImmobileFieldRefs {
  readonly id: Prisma.FieldRef<"ImmagineImmobile", 'String'>
  readonly immobileId: Prisma.FieldRef<"ImmagineImmobile", 'String'>
  readonly url: Prisma.FieldRef<"ImmagineImmobile", 'String'>
  readonly isCover: Prisma.FieldRef<"ImmagineImmobile", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"ImmagineImmobile", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"ImmagineImmobile", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ImmagineImmobile findUnique
 */
export type ImmagineImmobileFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ImmagineImmobile
   */
  select?: Prisma.ImmagineImmobileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ImmagineImmobile
   */
  omit?: Prisma.ImmagineImmobileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ImmagineImmobileInclude<ExtArgs> | null
  /**
   * Filter, which ImmagineImmobile to fetch.
   */
  where: Prisma.ImmagineImmobileWhereUniqueInput
}

/**
 * ImmagineImmobile findUniqueOrThrow
 */
export type ImmagineImmobileFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ImmagineImmobile
   */
  select?: Prisma.ImmagineImmobileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ImmagineImmobile
   */
  omit?: Prisma.ImmagineImmobileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ImmagineImmobileInclude<ExtArgs> | null
  /**
   * Filter, which ImmagineImmobile to fetch.
   */
  where: Prisma.ImmagineImmobileWhereUniqueInput
}

/**
 * ImmagineImmobile findFirst
 */
export type ImmagineImmobileFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ImmagineImmobile
   */
  select?: Prisma.ImmagineImmobileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ImmagineImmobile
   */
  omit?: Prisma.ImmagineImmobileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ImmagineImmobileInclude<ExtArgs> | null
  /**
   * Filter, which ImmagineImmobile to fetch.
   */
  where?: Prisma.ImmagineImmobileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ImmagineImmobiles to fetch.
   */
  orderBy?: Prisma.ImmagineImmobileOrderByWithRelationInput | Prisma.ImmagineImmobileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ImmagineImmobiles.
   */
  cursor?: Prisma.ImmagineImmobileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ImmagineImmobiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ImmagineImmobiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ImmagineImmobiles.
   */
  distinct?: Prisma.ImmagineImmobileScalarFieldEnum | Prisma.ImmagineImmobileScalarFieldEnum[]
}

/**
 * ImmagineImmobile findFirstOrThrow
 */
export type ImmagineImmobileFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ImmagineImmobile
   */
  select?: Prisma.ImmagineImmobileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ImmagineImmobile
   */
  omit?: Prisma.ImmagineImmobileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ImmagineImmobileInclude<ExtArgs> | null
  /**
   * Filter, which ImmagineImmobile to fetch.
   */
  where?: Prisma.ImmagineImmobileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ImmagineImmobiles to fetch.
   */
  orderBy?: Prisma.ImmagineImmobileOrderByWithRelationInput | Prisma.ImmagineImmobileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ImmagineImmobiles.
   */
  cursor?: Prisma.ImmagineImmobileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ImmagineImmobiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ImmagineImmobiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ImmagineImmobiles.
   */
  distinct?: Prisma.ImmagineImmobileScalarFieldEnum | Prisma.ImmagineImmobileScalarFieldEnum[]
}

/**
 * ImmagineImmobile findMany
 */
export type ImmagineImmobileFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ImmagineImmobile
   */
  select?: Prisma.ImmagineImmobileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ImmagineImmobile
   */
  omit?: Prisma.ImmagineImmobileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ImmagineImmobileInclude<ExtArgs> | null
  /**
   * Filter, which ImmagineImmobiles to fetch.
   */
  where?: Prisma.ImmagineImmobileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ImmagineImmobiles to fetch.
   */
  orderBy?: Prisma.ImmagineImmobileOrderByWithRelationInput | Prisma.ImmagineImmobileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ImmagineImmobiles.
   */
  cursor?: Prisma.ImmagineImmobileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ImmagineImmobiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ImmagineImmobiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ImmagineImmobiles.
   */
  distinct?: Prisma.ImmagineImmobileScalarFieldEnum | Prisma.ImmagineImmobileScalarFieldEnum[]
}

/**
 * ImmagineImmobile create
 */
export type ImmagineImmobileCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ImmagineImmobile
   */
  select?: Prisma.ImmagineImmobileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ImmagineImmobile
   */
  omit?: Prisma.ImmagineImmobileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ImmagineImmobileInclude<ExtArgs> | null
  /**
   * The data needed to create a ImmagineImmobile.
   */
  data: Prisma.XOR<Prisma.ImmagineImmobileCreateInput, Prisma.ImmagineImmobileUncheckedCreateInput>
}

/**
 * ImmagineImmobile createMany
 */
export type ImmagineImmobileCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ImmagineImmobiles.
   */
  data: Prisma.ImmagineImmobileCreateManyInput | Prisma.ImmagineImmobileCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ImmagineImmobile createManyAndReturn
 */
export type ImmagineImmobileCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ImmagineImmobile
   */
  select?: Prisma.ImmagineImmobileSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ImmagineImmobile
   */
  omit?: Prisma.ImmagineImmobileOmit<ExtArgs> | null
  /**
   * The data used to create many ImmagineImmobiles.
   */
  data: Prisma.ImmagineImmobileCreateManyInput | Prisma.ImmagineImmobileCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ImmagineImmobileIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ImmagineImmobile update
 */
export type ImmagineImmobileUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ImmagineImmobile
   */
  select?: Prisma.ImmagineImmobileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ImmagineImmobile
   */
  omit?: Prisma.ImmagineImmobileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ImmagineImmobileInclude<ExtArgs> | null
  /**
   * The data needed to update a ImmagineImmobile.
   */
  data: Prisma.XOR<Prisma.ImmagineImmobileUpdateInput, Prisma.ImmagineImmobileUncheckedUpdateInput>
  /**
   * Choose, which ImmagineImmobile to update.
   */
  where: Prisma.ImmagineImmobileWhereUniqueInput
}

/**
 * ImmagineImmobile updateMany
 */
export type ImmagineImmobileUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ImmagineImmobiles.
   */
  data: Prisma.XOR<Prisma.ImmagineImmobileUpdateManyMutationInput, Prisma.ImmagineImmobileUncheckedUpdateManyInput>
  /**
   * Filter which ImmagineImmobiles to update
   */
  where?: Prisma.ImmagineImmobileWhereInput
  /**
   * Limit how many ImmagineImmobiles to update.
   */
  limit?: number
}

/**
 * ImmagineImmobile updateManyAndReturn
 */
export type ImmagineImmobileUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ImmagineImmobile
   */
  select?: Prisma.ImmagineImmobileSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ImmagineImmobile
   */
  omit?: Prisma.ImmagineImmobileOmit<ExtArgs> | null
  /**
   * The data used to update ImmagineImmobiles.
   */
  data: Prisma.XOR<Prisma.ImmagineImmobileUpdateManyMutationInput, Prisma.ImmagineImmobileUncheckedUpdateManyInput>
  /**
   * Filter which ImmagineImmobiles to update
   */
  where?: Prisma.ImmagineImmobileWhereInput
  /**
   * Limit how many ImmagineImmobiles to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ImmagineImmobileIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ImmagineImmobile upsert
 */
export type ImmagineImmobileUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ImmagineImmobile
   */
  select?: Prisma.ImmagineImmobileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ImmagineImmobile
   */
  omit?: Prisma.ImmagineImmobileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ImmagineImmobileInclude<ExtArgs> | null
  /**
   * The filter to search for the ImmagineImmobile to update in case it exists.
   */
  where: Prisma.ImmagineImmobileWhereUniqueInput
  /**
   * In case the ImmagineImmobile found by the `where` argument doesn't exist, create a new ImmagineImmobile with this data.
   */
  create: Prisma.XOR<Prisma.ImmagineImmobileCreateInput, Prisma.ImmagineImmobileUncheckedCreateInput>
  /**
   * In case the ImmagineImmobile was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ImmagineImmobileUpdateInput, Prisma.ImmagineImmobileUncheckedUpdateInput>
}

/**
 * ImmagineImmobile delete
 */
export type ImmagineImmobileDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ImmagineImmobile
   */
  select?: Prisma.ImmagineImmobileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ImmagineImmobile
   */
  omit?: Prisma.ImmagineImmobileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ImmagineImmobileInclude<ExtArgs> | null
  /**
   * Filter which ImmagineImmobile to delete.
   */
  where: Prisma.ImmagineImmobileWhereUniqueInput
}

/**
 * ImmagineImmobile deleteMany
 */
export type ImmagineImmobileDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ImmagineImmobiles to delete
   */
  where?: Prisma.ImmagineImmobileWhereInput
  /**
   * Limit how many ImmagineImmobiles to delete.
   */
  limit?: number
}

/**
 * ImmagineImmobile without action
 */
export type ImmagineImmobileDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ImmagineImmobile
   */
  select?: Prisma.ImmagineImmobileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ImmagineImmobile
   */
  omit?: Prisma.ImmagineImmobileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ImmagineImmobileInclude<ExtArgs> | null
}
